title:
  title: "&4Jailbreak"
  subtitle: "&bFind a way to escape!"
requirements:
  feeLevel: 1
  feeMoney: 5.0
  permission: [test.node.1, test.node.2]
  groupSize:
    minimum: 1
    maximum: 2
  forbiddenItems:
    - IRON_SWORD
    - STONE
  keyItems:
    - DIAMOND
    - ANVIL
keepInventoryOnEnter: true
keepInventoryOnEscape: true
keepInventoryOnFinish: true
